o2cb service offlines if o2cb_ctl encounters any errors... like no local node found Signed-off-by: Sunil Mushran <sunil.mushran@oracle.com> Signed-off-by: Mark Fasheh <mark.fasheh@oracle.com>
Original-revision: 845

diff --git a/vendor/common/o2cb.init b/vendor/common/o2cb.init
--- a/vendor/common/o2cb.init
+++ b/vendor/common/o2cb.init
@@ -484,6 +484,17 @@ online()
 
     echo -n "Starting cluster ${CLUSTER}: "
     OUTPUT="`o2cb_ctl -H -n "${CLUSTER}" -t cluster -a online=yes 2>&1`"
+    if [ $? = 0 ]
+    then
+        echo "OK"
+        return
+    else
+        echo "Failed"
+        echo "$OUTPUT"
+    fi
+
+    echo -n "Stopping cluster ${CLUSTER}: "
+    OUTPUT="`o2cb_ctl -H -n "${CLUSTER}" -t cluster -a online=no 2>&1`"
     if_fail "$?" "$OUTPUT"
 }
 
