o More command options
Original-revision: 520

diff --git a/vendor/common/o2cb.init b/vendor/common/o2cb.init
--- a/vendor/common/o2cb.init
+++ b/vendor/common/o2cb.init
@@ -74,6 +74,107 @@ if_fail()
 
 
 #
+# write_sysconfig()
+#
+# Writes the system configuration out
+#
+write_sysconfig()
+{
+    echo -n "Writing O2CB configuration: "
+    cat >/etc/sysconfig/o2cb <<EOF
+#
+# This is a configuration file for automatic startup of the O2CB
+# driver.  It is generated by running /etc/init.d/oracleasm configure.
+# Please use that method to modify this file
+#
+
+# O2CB_ENABELED: 'true' means to load the driver on boot.
+O2CB_ENABLED=${O2CB_ENABLED:-false}
+
+# O2CB_BOOTCLUSTER: If not empty, the name of a cluster to start.
+O2CB_BOOTCLUSTER=${O2CB_BOOTCLUSTER}
+
+EOF
+
+    if [ $? != 0 ]
+    then
+        return 1
+    fi
+    return 0
+}
+
+#
+# configure_ask()
+#
+# Ask configuration questions, setting the shell vars.
+#
+configure_ask()
+{
+    cat <<EOF
+Configuring the O2CB driver.
+
+This will configure the on-boot properties of the O2CB driver.
+The following questions will determine whether the driver is loaded on
+boot.  The current values will be shown in brackets ('[]').  Hitting
+<ENTER> without typing an answer will keep that current value.  Ctrl-C
+will abort.
+
+EOF
+
+    while :
+    do
+        if [ "$O2CB_ENABLED" = "true" ]
+        then
+            CUR=y
+        else
+            CUR=n
+        fi
+        echo -n "Load O2CB driver on boot (y/n) [$CUR]: "
+        read LINE
+        case "$LINE" in
+        "")
+            break
+            ;;
+        y|Y)
+            O2CB_ENABLED=true
+            break
+            ;;
+        n|N)
+            O2CB_ENABLED=false
+            break
+            ;;
+        *)
+            echo "Invalid answer: $LINE" >&2
+            ;;
+        esac
+    done
+
+    while :
+    do
+        echo -n "Cluster to start on boot (Enter \"none\" to clear) [$O2CB_BOOTCLUSTER]: "
+        read LINE
+        case "$LINE" in
+        "")
+            break
+            ;;
+        none)
+            O2CB_BOOTCLUSTER=
+            break
+            ;;
+
+        *[^a-zA-Z0-9]*)
+            echo "Invalid cluster name: $LINE" >&2
+            ;;
+        *)
+            O2CB_BOOTCLUSTER="$LINE"
+            break
+            ;;
+        esac
+    done
+}
+
+
+#
 # dev_create()
 #
 # Create $1
@@ -97,7 +198,7 @@ dev_create()
         return 1
     fi
 
-    echo -n "Creating $DEV mount point "
+    echo -n "Creating $DEV mount point: "
     mkdir "$DEV" 2>/dev/null
     if [ $? != 0 ]
     then
@@ -129,7 +230,7 @@ load_module()
         return 2
     fi
 
-    echo -n "Loading module \"$MODNAME\" "
+    echo -n "Loading module \"$MODNAME\": "
     modprobe -s "$MODNAME"
     if [ "$?" != 0 ]
     then
@@ -173,7 +274,7 @@ unload_module()
         ;;
     esac
 
-    echo -n "Unloading module \"$MODNAME\" "
+    echo -n "Unloading module \"$MODNAME\": "
     modprobe -rs "$MODNAME"
     if [ "$?" != 0 ]
     then
@@ -209,7 +310,7 @@ mount_device()
         return 2
     fi
 
-    echo -n "Mounting ${TYPE} driver filesystem "
+    echo -n "Mounting ${TYPE} driver filesystem: "
     mount $OPTS -t ${TYPE} ${TYPE} $FULL_MOUNT
     if [ $? != 0 ]
     then
@@ -245,7 +346,7 @@ unmount_device()
         return 2
     fi
 
-    echo -n "Unmounting ${TYPE} driver filesystem "
+    echo -n "Unmounting ${TYPE} driver filesystem: "
     umount $FULL_MOUNT
     if [ $? != 0 ]
     then
@@ -278,7 +379,11 @@ load()
 
 online()
 {
-    CLUSTER="$1"
+    CLUSTER="${1:-${O2CB_BOOTCLUSTER}}"
+    if [ -z "$CLUSTER" ]
+    then
+        return
+    fi
 
     #
     # FIXME FIXME FIXME
@@ -289,6 +394,12 @@ online()
     echo -n "Starting cluster ${CLUSTER}: "
     OUTPUT="$(o2cb_ctl -H -l "${O2CB_MANAGER}" -n "${CLUSTER}" -t cluster -a online=yes 2>&1)"
     if_fail "$?" "$OUTPUT"
+}
+
+start()
+{
+    load
+    online "$2"
 }
 
 unload()
@@ -320,6 +431,18 @@ unload()
         unload_module "$MODULE_NAME"
         if_fail "$?"
     done
+}
+
+stop()
+{
+    unload
+}
+
+configure()
+{
+    configure_ask
+    write_sysconfig
+    if_fail "$?" "Unable to write the driver configuration"
 }
 
 status()
@@ -371,11 +494,7 @@ status()
 
 case "$1" in
     start)
-        load
-        if [ -n "$2" ]
-        then
-            online "$2"
-        fi
+        start
         ;;
 
     status)
@@ -383,7 +502,7 @@ case "$1" in
         ;;
 
     stop)
-        unload
+        stop
         ;;
 
     restart)
@@ -406,6 +525,31 @@ case "$1" in
     unload)
         unload
         ;;
+
+    configure)
+        configure
+        if [ "$O2CB_ENABLED" = "true" ]
+        then
+            start
+        else
+            stop
+        fi
+        ;;
+
+    enable)
+        O2CB_ENABLED=true
+        write_sysconfig
+        if_fail "$?" "Unable to write the driver configuration"
+        start
+        ;;
+
+    disable)
+        O2CB_ENABLED=false
+        write_sysconfig
+        if_fail "$?" "Unable to write the driver configuration"
+        stop
+        ;;
+
     *)
         echo "Usage: $0 {start|stop|restart|enable|disable|load|unload|status}"
         exit 1
