o2cb: Ignore files in cluster directory.
The cluster directory usually only contains subdirectories.  However,
if it were to contain an attribute file, libo2cb and o2cb.init will see it
as a cluster name.  Teach libo2cb to only look at S_ISDIR().  Teach
o2cb.init to only look at test -d.

Signed-off-by: Joel Becker <joel.becker@oracle.com>
Signed-off-by: Sunil Mushran <sunil.mushran@oracle.com>

diff --git a/vendor/common/o2cb.init b/vendor/common/o2cb.init
--- a/vendor/common/o2cb.init
+++ b/vendor/common/o2cb.init
@@ -865,8 +865,12 @@ unload()
     then
         ls -1 $(configfs_path)/cluster/ | while read CLUSTER
         do
-            echo "Unable to unload modules as O2CB cluster ${CLUSTER} is still online" >&2
-            exit 1
+            if [ ! -L "$(configfs_path)/cluster/${CLUSTER}" -a \
+                 -d "$(configfs_path)/cluster/${CLUSTER}" ]
+            then
+                echo "Unable to unload modules as O2CB cluster ${CLUSTER} is still online" >&2
+                exit 1
+            fi
         done
         if [ $? = 1 ]
         then
